name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install yt-dlp
        run: |
          Invoke-WebRequest -Uri https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe -OutFile yt-dlp.exe
          Move-Item -Path yt-dlp.exe -Destination $env:USERPROFILE\yt-dlp.exe
          $oldPath = [Environment]::GetEnvironmentVariable("Path", "User")
          $newPath = "$oldPath;$env:USERPROFILE"
          [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")

      - name: Run PowerShell script analysis
        run: |
          Install-Module -Name PSScriptAnalyzer -Force
          $results = Invoke-ScriptAnalyzer -Path .\yt-dlp-helper.ps1
          $results | Format-Table -AutoSize | Out-File -FilePath analysis-results.txt
          if ($results) { throw "Script analysis found issues" }

      - name: Upload analysis results
        uses: actions/upload-artifact@v2
        with:
          name: analysis-results
          path: analysis-results.txt

      - name: Test script with mock data
        run: |
          $mockUrl = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
          $mockInput = @"
          $mockUrl
          1
          y
          "@
          $mockInput | powershell -File .\yt-dlp-helper.ps1
          if (-not $?) { throw "Script execution failed" }
